---
# Ansible Galaxy requirements file
# Install with: ansible-galaxy install -r requirements.yml

# Collections
collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=7.0.0"

# Roles (if needed in the future)
roles: []

